In [87]:
# Import libraries
import pandas as pd
import numpy as np

In [88]:
# Load dataset

df=pd.read_csv('Dataset.csv')

In [89]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

**##Data Inspection**

In [90]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [92]:
df.shape

(103, 11)

In [93]:
#Check Duplicate Values
df["Order_ID"].duplicated().sum()

np.int64(3)

In [94]:
df[df["Order_ID"].duplicated()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [95]:
df[df["Order_ID"].duplicated(keep=False)]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [96]:
# Remove duplicate order IDs
df = df.drop_duplicates(subset=["Order_ID"])
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.40

In [97]:
#Check Missing Values
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [98]:
# Find negative value
df = df.copy()
# Ensure Quantity, Price, and Total are numeric before comparison
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Total'] = pd.to_numeric(df['Total'], errors='coerce')

# Find rows with negative values
negative_values = df[
    (df['Quantity'] < 0) |
    (df['Price'] < 0) |
    (df['Total'] < 0)
]

print(negative_values)

     ID  Customer_Name   Order_ID Order_Date  Product    Category  Quantity  \
17  117   Customer_117  ORD-72751  2/12/2025  Blender  electronic      -2.0
34  134   Customer_134  ORD-16585  10/4/2025  T-shirt    Clothing      -5.0
37  137   Customer_137  ORD-91254  2/23/2025   Vacuum        Home       3.0

       Price    Payment_Method      Status     Total
17  10000.00  Cash on Delivery  Processing -20000.00
34    591.53            PayPal     Shipped  -2957.65
37   -100.00  Cash on Delivery   Delivered   -300.00

In [99]:
# Handle mixed date formats
df = df.copy()
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce", format="mixed", dayfirst=True)
df = df[df["Order_Date"].notna()].copy()
df["Order_Date"] = df["Order_Date"].dt.strftime("%d-%m-%Y")

df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,22-11-2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,23-12-2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,19-03-2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,20-10-2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,19-06-2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,23-12-2024,Vacuum,Home,NaN,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,23-06-2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,27-07-2025,Vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,22-01-2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [100]:
# Clean category column

df[" Category"] = df[" Category"].astype(str).str.strip().str.lower()

category_map = {"sport": "Sports","electronic": "Electronics"}
df[" Category"] = df[" Category"].replace(category_map)
product_to_category = {"Laptop": "Electronics","Smartphone": "Electronics","Vacuum": "Home","Shoes": "Clothing","Jeans": "Clothing","Biography": "Books",
                       "Headphones":"Electronics","Basketball": "Sports","Yoga Mat":"Sports"}
df[" Category"] = df.apply(lambda row: product_to_category.get(row["Product"], row[" Category"]),axis=1)
df[" Category"] = df[" Category"].str.title()

df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,22-11-2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,23-12-2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,19-03-2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,20-10-2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,19-06-2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,23-12-2024,Vacuum,Home,NaN,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,23-06-2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,27-07-2025,Vacuum,Home,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,22-01-2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [101]:
# Clean quantity column
# make sure Quantity is numeric
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

# replace negative values with NaN
df.loc[df["Quantity"] < 0, "Quantity"] = np.nan

# fill missing values with mode
mode_value = df["Quantity"].mode()[0]
df["Quantity"] = df["Quantity"].fillna(mode_value)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,22-11-2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,23-12-2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,19-03-2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,20-10-2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,19-06-2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,23-12-2024,Vacuum,Home,5.0,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,23-06-2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,27-07-2025,Vacuum,Home,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,22-01-2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [102]:
# Clean price column
# Remove extreme price outlier
df = df[~(df['Price'] > 5000)].copy()

# Combine string cleaning and numeric conversion into one step
cleaned_price_series = df['Price'].astype(str).str.replace(r'[^0-9.]', '', regex=True)
df.loc[:, 'Price'] = pd.to_numeric(cleaned_price_series, errors='coerce')


# Fill missing values and round
df.loc[:, 'Price'] = df['Price'].fillna(df['Price'].mean()).round(2)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,22-11-2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,518.60,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,23-12-2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,19-03-2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,20-10-2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,19-06-2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,23-12-2024,Vacuum,Home,5.0,518.60,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,23-06-2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,27-07-2025,Vacuum,Home,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,22-01-2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [103]:
# Create total column
df["Total"] = (df["Quantity"] * df["Price"]).round(2)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,22-11-2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,518.60,PayPal,Processing,1037.20
2,102,Customer_102,ORD-84355,23-12-2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,19-03-2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,20-10-2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,19-06-2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,23-12-2024,Vacuum,Home,5.0,518.60,PayPal,Delivered,2593.00
97,197,Customer_197,ORD-79139,23-06-2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,27-07-2025,Vacuum,Home,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,22-01-2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [104]:
df[['Quantity','Price','Total']].describe().round(2)

       Quantity   Price    Total
count     98.00   98.00    98.00
mean       3.18  518.60  1686.26
std        1.54  250.15  1197.47
min        1.00   38.00    40.95
25%        2.00  337.82   716.82
50%        3.00  520.31  1439.13
75%        5.00  703.24  2593.00
max        5.00  978.63  4893.15

In [105]:
df.to_csv("cleaned_data.csv", index=False)